### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by donnydark0** [0x7df/0x7df.github.io#1]
Hi, this is the only way I found to contact you. In 2017 you made a guide how to automate exporting PDFs in Safari. This is exactly what I am looking for to quickly save newspaper articles to Nextcloud. I am on Big Sur and it doesn't seem to work anymore? Any chance you might update this?

Best regards

(Scripting Safari's Export to PDF function on a Mac, Sun 06 August 2017)

**Comment by 0x7df** [comment]
Hi, the post has been update to include a fix for this. Thanks.
